### ISSUE TITLE
Weight being ignored?

### ISSUE THREAD

**Issue by Kiyaku** [codetaylor/hookt#4]
Heya,

was trying out a few test examples but it seems like weight is either being ignored, or i'm doing something wrong/misunderstand the use of it;. 

This is the script i'm using:
```
{
  "rules": [
    {
      "drops": [
        {
          "item": {
            "selector": {
              "weight": {
                "value": 1000
              }
            },
            "items": [
              "minecraft:diamond"
            ]
          }
        },
        {
          "item": {
            "items": [
              "minecraft:string"
            ]
          }
        }
      ]
    }
  ]
}
``` 

I do get both items, but pretty much at a 50:50 chance. I tried to add a weight selector to the string entry with a weight value of 1 as well, but that didn't make a difference. Shouldn't this make the diamond show up much more often than the string?

The example should be similar to the example on this page. 

Wasn't sure if you are still planning on working on this mod (really hope you do heh), but figured i'll post it anyway, just in case. 

Thanks a lot,
SC

**Comment by codetaylor** [comment]
I copied the rule you supplied, added the debug flag, and inspected the `hookt.log` and found some suspicious looking entries:

```text
[DEBUG] [DROP] [SELECTOR] [OK] Required luck level met: (required) 0 <= 3 (candidate)
[DEBUG] [DROP] Added drop to weighted picker: RuleDropItem{_items=[1xitem.diamond@0], quantity=RandomLuckInt{fixed=1, min=0, max=0, luckModifier=0}}
[DEBUG] [DROP] Added drop using weight value: 1
[DEBUG] [DROP] [SELECTOR] [OK] Required luck level met: (required) 0 <= 3 (candidate)
[DEBUG] [DROP] Added drop to weighted picker: RuleDropItem{_items=[1xitem.string@0], quantity=RandomLuckInt{fixed=1, min=0, max=0, luckModifier=0}}
[DEBUG] [DROP] Added drop using weight value: 1
[DEBUG] [DROP] Valid drop candidates found: 2
[DEBUG] [DROP] Total weight: 2
```

So, it looks like the weight is using the default value of `1`.

Then I compared your item definitions with the syntax and noticed that your `selector` is in the wrong scope.

Then I looked at the example... #feelsbadman

The example is wrong.

**Comment by codetaylor** [comment]
I fixed the example and can confirm that fixing the scope of the `selector` produces the expected results:

```text
[DEBUG] [DROP] [SELECTOR] [OK] Required luck level met: (required) 0 <= 3 (candidate)
[DEBUG] [DROP] Added drop to weighted picker: RuleDropItem{_items=[1xitem.diamond@0], quantity=RandomLuckInt{fixed=1, min=0, max=0, luckModifier=0}}
[DEBUG] [DROP] Added drop using weight value: 1000
[DEBUG] [DROP] [SELECTOR] [OK] Required luck level met: (required) 0 <= 3 (candidate)
[DEBUG] [DROP] Added drop to weighted picker: RuleDropItem{_items=[1xitem.string@0], quantity=RandomLuckInt{fixed=1, min=0, max=0, luckModifier=0}}
[DEBUG] [DROP] Added drop using weight value: 1
[DEBUG] [DROP] Valid drop candidates found: 2
[DEBUG] [DROP] Total weight: 1001
```

**Comment by Kiyaku** [comment]
Ohh well that would explain it! Thanks a lot, that fixed it (and even makes much more sense to have it outside the item definition haha). 

Appreciate it!
