### ISSUE TITLE
Possible to add a flag to make fished items unburnable? 

### ISSUE THREAD

**Issue by Kiyaku** [codetaylor/hookt#5]
Hey,

i'm trying to use the mod Combustion Fishing with hookt, to get a way of fishing in the nether/lava. The loottables seem to work fine, but the items would burn up in the lava once you reel them in. 
I believe Combustion Fishing marks their items as setEntityInvulnerable(true) to prevent this. 

Would it be possible to get an extra entry in "IRuleDropItem" (or whereever it makes the most sense) to mark items as invulnerable? Was checking if there is a way to do it with NBT alone, but afaik, there isn't unfortunately. 

Cheers,
SC

**Comment by codetaylor** [comment]
I think this is doable, can't guarantee how soon though.

**Comment by Kiyaku** [comment]
Sweet, appreciate that you are considering it at least, thanks!

**Comment by codetaylor** [comment]
Feature added in 1.12.2-1.1.0

**Comment by codetaylor** [comment]
Drops can be flagged as invulnerable, but at the Rule level and not the RuleDropItem level.

I also added a config option for direct-to-inventory drops from fishing.

**Comment by SeriousCreeper** [comment]
Very cool, thanks a lot, this is gonna help a ton!

**Comment by codetaylor** [comment]
@Kiyaku I didn't have any time to test it, so please let me know if anything fails or doesn't behave as expected.

**Comment by SeriousCreeper** [comment]
Just gave it a shot, seems to work great! I like the direct-to-inventory setting too, that's gonna work great with mods like realistic physics, as they usually make the fish get stuck on water surfaces and not reel them in properly.
