### ISSUE TITLE
Industrial Foregoing Compatibility

### ISSUE THREAD

**Issue by TomShkurti** [codetaylor/hookt#6]
The "Resources Fisher" block from Industrial Foregoing is not affected by hookt's scripts and will always return fish from the default list.

**Comment by codetaylor** [comment]
Industrial Foregoing (IF) uses loot tables to determine what drops: https://github.com/Buuz135/Industrial-Foregoing/blob/master/src/main/java/com/buuz135/industrial/tile/agriculture/WaterResourcesCollectorTile.java#L86

Hookt uses the ItemFishedEvent: https://github.com/codetaylor/hookt/blob/master/src/main/java/com/codetaylor/mc/hookt/modules/hookt/events/EventHandler.java#L44

Unfortunately, not much that Hookt can do about that.

~If IF were to run the results of the loot table through the ItemFishedEvent, Hookt would be able to influence the drops.~

I take that back - still wouldn't work.
