### ISSUE TITLE
Drop removal possible?

### ISSUE THREAD

**Issue by WrongWeekend** [codetaylor/hookt#8]
I know this mod can replace fishing drops with other items, but what about eliminating or reducing the possibility of getting certain drops or any drops at all under certain conditions?

To be more specific about my goal, I want to make it so that no fishing loot of any kind can be acquired outside of river/ocean biomes, and to make rivers only yield a smaller amount of salmon, and oceans to yield a slightly reduced chance of only the four types of fish.

**Comment by codetaylor** [comment]
Yes, you can do all of that.
